### ISSUE TITLE
Port IsAfter

### ISSUE THREAD

**Issue by ByteBlast** [ByteBlast/Validator#10]
Implement `IsAfter` from [validator.js](https://github.com/chriso/validator.js) in this library.

> **isAfter(str [, date])** - check if the string is a date that's after the specified date (defaults to now).

**Comment by PrasadHonrao** [comment]
Do you really want to keep first parameter as of type String rather than DateTime?

**Comment by ByteBlast** [comment]
Maybe we should overload the method? 

Have one overload that takes a `string` and another that takes a `DateTime`. 

I think there is value in accommodating a `string`, the input may come from a Console, for example.
