### ISSUE TITLE
Slight difference between isFQDN in Validator.js and IsFqdn in Validator?

### ISSUE THREAD

**Issue by s-moon** [ByteBlast/Validator#38]
Whilst looking at the source for IsFqdn in the C# project, I noticed a small difference where it tests for "--" at the end of the method. 

In the Javascript function, validator.isFQDN it has:
  part[part.length - 1] === '-'
but in the C# project, it has:
  copy.EndsWith("--")

Should this instead be: 
  copy.EndsWith("-")

With only one hyphen?

**Comment by ByteBlast** [comment]
I believe @ledbutter wrote the implementation for this method. @ledbutter maybe you could take a look @ this?

@s-moon, I wonder, are the tests the same? If yes, this is likely a non-issue. 

(I will investigate further myself if noone else wants to - I am afk at the moment)

**Comment by s-moon** [comment]
With or without the change to the double-hyphen, the tests ran perfectly. But, I don't believe there is specific test for that failure case, as far as I can see, so it would anyway.

Test cases on Validator.js match your C# version.
