### ISSUE TITLE
Port IsUrl

### ISSUE THREAD

**Issue by ByteBlast** [ByteBlast/Validator#6]
Implement `isURL` from [validator.js](https://github.com/chriso/validator.js) in this library.

**Comment by PrasadHonrao** [comment]
I am taking this one

**Comment by ByteBlast** [comment]
Thanks to @PrasadHonrao we have an almost complete implementation of this method.

There are however, a couple of limitations compared to the original library. 

In commit `2388e1` I added some tests to demonstrate the limitations that need to be removed before we can close this issue.

```c#
[Theory(Skip = "Awaiting fix.")]
[InlineData("xyz://foobar.com", false,)]
[InlineData("valid.au", true)]
[InlineData("foobar.com/", true)]
[InlineData("foobar.com", true)]
public void IsUrl2(string url, bool expected)
{
    var actual = Validator.IsUrl(url);
    Assert.Equal(expected, actual);
}
```

@PrasadHonrao, if you want to take ownership of this this then great! Otherwise, no worries -- I will have to take a look at this myself in the future.
