### ISSUE TITLE
Port IsUuid

### ISSUE THREAD

**Issue by ByteBlast** [ByteBlast/Validator#8]
Implement `isUUID` from [validator.js](https://github.com/chriso/validator.js) in this library.

**Comment by orangutanboy** [comment]
I'd like to implement this, how do I go about getting assigned? I have looked for instructions but couldn't find any...

**Comment by ByteBlast** [comment]
Hi @orangutanboy. I appreciate you showing an interest in the project :smile:.

> I'd like to implement this, how do I go about getting assigned?

There is no need to be assigned in this case. 

Simply [fork](https://github.com/ByteBlast/Validator/fork) this repository, make your changes, and then issue a [pull request](https://help.github.com/articles/using-pull-requests/).

**Comment by orangutanboy** [comment]
Great, thanks
